name: Frontend CI

on: 
  push:
    branches:
      - main
      
  # Automatic trigger on pull requests that are closed to the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/frontend

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js 
          uses: actions/setup-node@v3
          with:
            node-version: latest
        
        - name: Install dependencies
          run: npm ci
        
        - name: Run linting
          run: npm run lint
    
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js 
          uses: actions/setup-node@v3
          with:
            node-version: latest
        
        - name: Install dependencies
          run: npm ci
        
        - name: Run test
          run: CI=true npm test